Flask-Project/app/auth.py
from flask_wtf import FlaskForm
from flask import request,flash

from wtforms.validators import InputRequired, Length, ValidationError
from flask import Blueprint, render_template, redirect, url_for
from flask_login import UserMixin, LoginManager, login_user, login_required, logout_user
from flask_login import current_user
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError
from wtforms.validators import InputRequired, Length, Email, EqualTo




from . import db
from .models import User
from . import bcrypt

auth = Blueprint('auth', __name__)
"""
login_manager = LoginManager()
login_manager.init_app()
login_manager.login_view = 'login' 

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
c

"""


@auth.route("/login", methods=['GET', 'POST'])
def login():

    # using FlaskForm to create a login form for the page
    class LoginForm(FlaskForm):
        username = StringField(validators=[
            InputRequired(), Length(min=4, max=20)], render_kw={"placeholder": "Username"})

        password = PasswordField(validators=[
            InputRequired(), Length(min=8, max=20)], render_kw={"placeholder": "Password"})

        submit = SubmitField('Login')

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user, remember=True)
                return redirect(url_for('views.chat'))
            else:
                flash('Invalid password', 'error')
        
        else:
            flash('Invalid username', 'error')

    if (current_user.is_authenticated):
        return redirect('/chat')
    else:
        return render_template("login.html", form=form, user=current_user)


# sign up route
@auth.route('/signup', methods=['GET','POST'])
def signup():
    # flask form to create the signup form
    class SignupForm(FlaskForm):
        # fields for first name, last name, email, and confirm password
        first_name = StringField(validators=[
                           InputRequired(), Length(max=50)], render_kw={"placeholder": "First Name"})
        last_name = StringField(validators=[
                           InputRequired(), Length(max=50)], render_kw={"placeholder": "Last Name"})
        email = StringField(validators=[
                           InputRequired(), Email(), Length(max=120)], render_kw={"placeholder": "Email"})
        username = StringField(validators=[
                           InputRequired(), Length(min=4, max=20)], render_kw={"placeholder": "Username"})
        password = PasswordField(validators=[
                             InputRequired(), Length(min=8, max=20)], render_kw={"placeholder": "Password"})
        confirm_password = PasswordField(validators=[
                             InputRequired(), EqualTo('password', message='Passwords must match')], render_kw={"placeholder": "Confirm Password"})
        
        
        submit = SubmitField('Register')

    form = SignupForm()

    if request.method == "POST":
        if form.validate_on_submit():
            email = form.email.data
            username = form.username.data

            # Check if email or username is already taken
            existing_user_email = User.query.filter_by(email=email).first()
            existing_user_username = User.query.filter_by(username=username).first()

            if existing_user_email:
                flash('Email is already taken. Please try again', 'error')
            elif existing_user_username:
                flash('Username is already taken. Please try again', 'error')
            else:
                # Both email and username are available, proceed with user creation
                hashed_password = bcrypt.generate_password_hash(form.password.data)
                new_user = User(
                    first_name=form.first_name.data,
                    last_name=form.last_name.data,
                    email=email,
                    username=username,
                    password=hashed_password
                )
                db.session.add(new_user)
                db.session.commit()
                return redirect(url_for('auth.login'))

    if current_user.is_authenticated:
        return redirect('/chat')
    else:
        return render_template("signup.html", form=form, user=current_user)

   # validation function for signup username; validation mainly checks whether user already exists


def validate_username(self, username):
    existing_user_username = User.query.filter_by(
        username=username.data).first()
    if existing_user_username:
        raise ValidationError(
            'That username already exists. Please choose a different one.')

   

# logout route
@auth.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login', user=current_user))

from flask import jsonify

@auth.route('/check_availability', methods=['POST'])
def check_availability():
    email = request.form['email']
    username = request.form['username']
    
    # Perform the necessary logic to check if the email and username are available
    # This could involve querying the database or any other checks
    
    # Example logic to check if the email is already taken
    email_taken = User.query.filter_by(email=email).first() is not None
    
    # Example logic to check if the username is already taken
    username_taken = User.query.filter_by(username=username).first() is not None
    
    response = {
        'email_taken': email_taken,
        'username_taken': username_taken
    }
    
    return jsonify(response)

Flask-Project/app/views.py
#creating blueprint for navigation routes 
from flask import Blueprint, render_template, redirect
from . import db
from flask_login import login_required, current_user
from flask import request
from .models import Message
import json


views = Blueprint('views', __name__)

@views.route('/')
def index():
    if current_user.is_authenticated: 
        return redirect("/chat")
    else:
        return render_template("main.html", user=current_user)


@views.route("/chat", methods=['GET', "POST"])
@login_required
def chat():
    # rendering chat page with current user login details

    #loading old messages
    items = Message.query.filter_by(user_id=current_user.id).order_by(Message.created_at.desc()).limit(10).all()

    return render_template("chat.html", user=current_user, messages=items)  

@views.route("/send_chat", methods=['POST'])
def send_chat():

    data = request.get_data()
    data = data.decode('utf-8')

    data = json.loads(data)

    new_message = Message(user_id=current_user.id, content=data["content"], isUser=data["isUser"])
    db.session.add(new_message)
    db.session.commit()

    return "message received"

@views.route("/features")
def features():

    return render_template("features.html",user=current_user)

Flask-Project/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- bootstrap cdn link -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <!-- link for stylesheet -->
    <link
      href="{{ url_for('static', filename='css/nav.css') }}"
      rel="stylesheet"
    />
    <link
      href="{{ url_for('static', filename='css/base.css') }}"
      rel="stylesheet"
    />
    
    <style></style>

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Italiana&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Island+Moments&display=swap"
      rel="stylesheet"
    />
    <link
    href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
    rel="stylesheet"
  />
    <style></style>
    {%block head%} {%endblock%}
  </head>
  <body>
    <!-- 3 bootstrap scripts -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>

    <!-- Navbar-->
    <nav class="nav-custom navbar navbar-expand-lg navbar-light bg-light">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarTogglerDemo01"
        aria-controls="navbarTogglerDemo01"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a
          class="navbar-brand"
          href="{{url_for('views.index')}}"
          style="
            font-family: 'Italiana', serif;
            font-size: 30px;
            font-weight: bold;
          "
          >CookStir</a
        >
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          {% if not user.is_authenticated%}
          <li class="nav-item active">
            <a
              class="nav-link"
              href="{{url_for('views.index')}}"
              style="
                font-family: 'Italiana', serif;
                font-size: 20px;
                font-weight: bold;
              "
              >Home<span class="sr-only"></span
            ></a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link"
              href="{{url_for('auth.login')}}"
              style="
                font-family: 'Italiana', serif;
                font-size: 20px;
                font-weight: bold;
              "
              >Login</a
            >
          </li>
          <li class="nav-item"></li>

          <li class="nav-item">
            <a
              class="nav-link"
              href="{{url_for('views.features')}}"
              style="
                font-family: 'Italiana', serif;
                font-size: 20px;
                font-weight: bold;
              "
              >Features</a
            >
          </li>
          {% else %}
          <li class="nav-item">
            <a
              class="nav-link"
              href="{{url_for('views.chat')}}"
              style="
                font-family: 'Italiana', serif;
                font-size: 20px;
                font-weight: bold;
              "
              >Chat</a
            >
          </li>
          <li class="nav-item">
            <a
              class="nav-link"
              href="{{url_for('auth.logout')}}"
              style="
                font-family: 'Italiana', serif;
                font-size: 20px;
                font-weight: bold;
              "
              >Logout</a
            >
          </li>
          {%endif%}
        </ul>
        {% if user.is_authenticated%}
        <div class="dropdown">
          <button
            class="btn btn-success dropdown-toggle"
            type="button"
            id="userDropdown"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              fill="currentColor"
              class="bi bi-person-circle"
              viewBox="0 0 16 16"
            >
              <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
              <path
                fill-rule="evenodd"
                d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"
              />
            </svg>
          </button>
          <div
            class="dropdown-menu dropdown-menu-right"
            aria-labelledby="userDropdown"
          >
            <h6 class="dropdown-header">User Details</h6>
            <a class="dropdown-item" href="#"
              >First Name: {{ user.first_name }}</a
            >
            <a class="dropdown-item" href="#"
              >Last Name: {{ user.last_name }}</a
            >
            <a class="dropdown-item" href="#">Email: {{ user.email }}</a>
            <!-- Add more user details as needed -->
          </div>
        </div>
        {%endif %}
      </div>
    </nav>
    <div>{%block body%}{%endblock%}</div>
  </body>
</html>

Flask-Project/app/templates/chat.html
{% extends 'base.html' %} {% block head %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/main.css') }}"
/>
<style>
  body {
    background-image: url("{{ url_for('static', filename='images/handrawn-barbecue-elements.jpg') }}");
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;
  }
  body {
    background-image: url("{{ url_for('static', filename='images/handrawn-barbecue-elements.jpg') }}");
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;
  }

  .container {
    max-width: 800px;
    padding: 0 15px;
    width: 100%;
    flex-grow: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }

  .navbar {
    width: 100%;
    position: fixed;
    top: 0;
    left: 0;
    z-index: 100;
    background-color: rgba(226, 83, 83, 0.997);
  }

  .user-message {
    align-self: flex-end;
  }
</style>
<!-- Include Bootstrap CSS -->
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
  integrity="sha384-pzjw8f+uael5+6BdZv2b8g5f7U2/LX+qwT5vkzJl5fCjrU4hDb5g9z+nksGkeTIJ"
  crossorigin="anonymous"
/>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Recipe Chatbot</title>
<link rel="stylesheet" href="{{ url_for('static',filename='css/chat.css')}}" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{{ url_for('static',filename='js/chat.js')}}"></script>
<style>
  body {
    display: flex;
    flex-direction: column;
  }
</style>
{% endblock %} {% block body %}
<div class="container">
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Chat with our AI</title>
      <link
        rel="stylesheet"
        href="{{ url_for('static',filename='css/chat.css')}}"
      />
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="{{ url_for('static',filename='js/chat.js')}}"></script>
    </head>
    <body>
      <div class="chat-container" style="margin-top: 100px">
        <div id="chat-box">
          <div class="message bot-message">
            Enter a recipe name that you are looking for, or switch to a
            different mode from the drop down menu below!"
          </div>
          {% for message in messages|reverse %}
          <div
            style="background-color: lightgrey"
            {%
            if
            message.isUser
            %}class="message user-message"
            {%else%}class="message bot-message"
            {%
            endif
            %}
          >
            {{ message.content | safe}}
          </div>
          {% endfor %}
        </div>
        <div id="input-forms" style="display: flex; justify-content: center">
          <form method="post">
            <input
              type="text"
              id="user-input"
              placeholder="Type your message"
              name="message"
              style="border: 1px solid black; width: 300px"
            />

            <submit id="send-btn" style="margin: 10px">Send</submit>
          </form>

          <select id="mode-select" style="margin: 10px">
            <option value="" disabled>Choose a mode</option>
            <option value="recipeName" selected>Recipe Name</option>
            <option value="ingredients">Ingredients</option>
            <option value="type">Search by Type</option>
          </select>
          <button
            id="regenerate-btn"
            style="
              background-color: #007bff;
              margin: 10px;
              color: white;
              border: 0px;
            "
          >
            Show More
          </button>
        </div>
      </div>
    </body>
  </html>

  {%endblock%}
</div>

Flask-Project/app/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DashBoard</title>
  </head>
  <body>
    <h1>You are logged in!</h1>
    <a href="{{url_for( 'logout')}}">logout</a>
  </body>
</html>

Flask-Project/app/templates/features.html
{% extends 'base.html' %} {% block head %}
<title>Features</title>
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/main.css') }}"
/>
<style>
  body {
    background-image: url("{{ url_for('static', filename='images/handrawn-barbecue-elements.jpg') }}");
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;
  }
</style>
{% endblock %} {% block body %}
<div class="container mt-4">
  <h1
    class="text-center"
    style="
      font-family: 'Montserrat', sans-serif;
      font-weight: bolder;
      color: white;
    "
  >
    Features
  </h1>

  <div
    class="card mb-4"
    style="
      font-family: 'Montserrat', sans-serif;
      font-weight: bolder;
      background-color: rgba(226, 83, 83, 0.997);
      border-radius: 5px;
      color: white;
    "
  >
    <div class="card-body">
      <h5
        class="card-title"
        style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
      >
        Recipe Chatbot
      </h5>
      <p
        class="card-text"
        style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
      >
        Interact with our intelligent chatbot to get recipe recommendations,
        ingredient suggestions, and nutritional information.
      </p>
    </div>
  </div>

  <div
    class="card mb-4"
    style="
      font-family: 'Montserrat', sans-serif;
      font-weight: bolder;
      background-color: rgba(226, 83, 83, 0.997);
      border-radius: 5px;
      color: white;
    "
  >
    <div class="card-body">
      <h5
        class="card-title"
        style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
      >
        Recipe Recommendations
      </h5>
      <p
        class="card-text"
        style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
      >
        Ask the chatbot for personalized recipe recommendations based on your
        preferences, such as specific ingredients, dietary restrictions, or
        cuisine types.
      </p>
    </div>
  </div>

  <div
    class="card mb-4"
    style="
      font-family: 'Montserrat', sans-serif;
      font-weight: bolder;
      background-color: rgba(226, 83, 83, 0.997);
      border-radius: 5px;
      color: white;
    "
  >
    <div class="card-body">
      <h5
        class="card-title"
        style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
      >
        Ingredient Suggestions
      </h5>
      <p
        class="card-text"
        style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
      >
        Get ingredient suggestions from the chatbot based on what you have in
        your pantry or specific ingredients you want to use in a recipe.
      </p>
    </div>
  </div>

  <div
    class="card mb-4"
    style="
      font-family: 'Montserrat', sans-serif;
      font-weight: bolder;
      background-color: rgba(226, 83, 83, 0.997);
      border-radius: 5px;
      color: white;
    "
  >
    <div class="card-body">
      <h5 class="card-title" style="font-weight: bolder">Food Types</h5>
      <p class="card-text" style="font-weight: bolder">
        Request a culinary category from the chatbot, and it will provide you
        with a delectable recipe suggestion tailored to your chosen category.
      </p>
    </div>
  </div>
  <div
    class="card mb-4"
    style="
      font-family: 'Montserrat', sans-serif;
      font-weight: bolder;
      background-color: rgba(226, 83, 83, 0.997);
      border-radius: 5px;
      color: white;
    "
  >
    <div class="card-body">
      <h5
        class="card-title"
        style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
      >
        Easy Interaction
      </h5>
      <p
        class="card-text"
        style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
      >
        Simply type your message in the chat input and click "Send" to interact
        with the chatbot. It will respond with relevant information in
        real-time.
      </p>
    </div>
  </div>
</div>
{% endblock %}

Flask-Project/app/templates/login.html
{% extends 'base.html' %} {% block head %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/main.css') }}"
/>
<title>Login</title>
<style>
  body {
    background-image: url("{{ url_for('static', filename='images/handrawn-barbecue-elements.jpg') }}");
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;
  }
</style>
{% endblock %} {% block body %}
<div class="container">
  <div
    class="row justify-content-center align-items-center"
    style="height: 100vh"
  >
    <div
      class="col-lg-4 mx-auto my-5 p-4"
      style="background-color: rgba(226, 83, 83, 0.997); border-radius: 5px"
    >
      <div class="login text-center">
        <h1 style="font-family: 'Montserrat', sans-serif; font-weight: bolder">
          Login
        </h1>
        <form method="POST" action="" class="loginform">
          {{ form.hidden_tag() }}
          <div
            class="form-group"
            style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
          >
            {{ form.username.label }} {{ form.username(class="form-control") }}
          </div>
          <div class="form-group" style="font-weight: bolder">
            {{ form.password.label }} {{ form.password(class="form-control") }}
          </div>
          {% with messages = get_flashed_messages() %} {% if messages %}
          <ul class="messages" style="text-align: center;">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
          </ul>
          {% endif %} {% endwith %}

          <div
            class="form-group"
            style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
          >
            {{ form.submit(class="btn btn-primary") }}
          </div>
        </form>
        <a
          href="{{ url_for('auth.signup') }}"
          style="
            font-family: 'Montserrat', sans-serif;
            font-weight: bolder;
            color: darkblue;
          "
          >Don't have an account? Sign Up.</a
        >
      </div>
    </div>
  </div>
</div>
{% endblock %}

Flask-Project/app/templates/main.html
{% extends 'base.html' %} {% block head %}
<link
  href="{{ url_for('static', filename='css/main.css') }}"
  rel="stylesheet"
/>
<title>Home</title>
{% endblock %} {% block body %}

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-6 d-flex flex-column justify-content-center">
      <h1
        class="text-center"
        style="font-family: 'Italiana', serif; font-size: 70px"
      >
        The New Way Of
        <span style="color: rgba(226, 83, 83, 0.997)">Cooking</span>
      </h1>
      <p
        class="text-center"
        style="font-size: 70px; font-family: 'Island Moments', cursive"
      >
        Create culinary magic with what's already in your pantry!<br />
        Find your ideal dish today!
      </p>
      <form action="{{url_for('auth.signup')}}" class="text-center">
        <input
          type="submit"
          value="Sign Up!"
          class="btn btn-primary"
          style="
            font-size: 30px;
            font-family: 'Italiana', serif;
            padding: 10px 20px;
            background-color: rgba(226, 83, 83, 0.997);
          "
        />
      </form>
    </div>

    <div class="col-lg-6">
      <img
        class="img-fluid"
        src="{{ url_for('static', filename='images/main_page_cooking_image.png') }}"
        alt="Cooking Image"
      />
    </div>
  </div>

  <div
    class="row mt-5"
    style="
      background-color: #3f3dcd;
      color: rgb(218, 218, 218);
      height: 80vh;
      display: flex;
      align-items: center;
    "
  >
    <div class="col">
      <h1
        class="text-center"
        style="font-family: 'Montserrat', sans-serif; font-size: 70px"
      >
        Instant Recipe Ideas
      </h1>
      <p
        class="text-center"
        style="
          font-size: 30px;
          font-family: 'Montserrat', sans-serif;
          font-size: 50px;
        "
      >
        Simply enter the ingredients you have at home and we'll suggest a range
        of tasty dishes you can make!
      </p>
    </div>
  </div>

  {% endblock %}
</div>

Flask-Project/app/templates/signup.html
{% extends 'base.html' %} {% block head %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/main.css') }}"
/>
<title>Sign-Up</title>
<style>
  body {
    background-image: url("{{ url_for('static', filename='images/handrawn-barbecue-elements.jpg') }}");
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;
  }
</style>
{% endblock %} {% block body %}
<div class="container">
  <div
    class="row justify-content-center align-items-center"
    style="height: 100vh"
  >
    <div
      class="col-lg-4 mx-auto my-5 p-4"
      style="
        background-color: rgba(226, 83, 83, 0.997);
        border-radius: 5px;
        font-family: 'Montserrat', sans-serif;
      "
    >
      <div class="login text-center">
        <h1 style="font-family: 'Montserrat', sans-serif; font-weight: bolder">
          Sign-Up
        </h1>
        <form action="" method="POST" class="signupform">
          <div
            class="form-group"
            style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
          >
            <label for="first_name">First Name</label>
            {{ form.first_name(class="form-control", placeholder="First Name")
            }}
          </div>
          <div
            class="form-group"
            style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
          >
            <label for="last_name">Last Name</label>
            {{ form.last_name(class="form-control", placeholder="Last Name") }}
          </div>
          <div
            class="form-group"
            style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
          >
            <label for="email">Email</label>
            {{ form.email(class="form-control", placeholder="Email") }}
          </div>
          <div
            class="form-group"
            style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
          >
            <label for="username">Username</label>
            {{ form.username(class="form-control", placeholder="Username") }}
          </div>
          <div
            class="form-group"
            style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
          >
            <label for="password">Password</label>
            {{ form.password(class="form-control", placeholder="Password") }}
          </div>
          <div
            class="form-group"
            style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
          >
            <label for="confirm_password">Confirm Password</label>
            {{ form.confirm_password(class="form-control", placeholder="Confirm
            Password") }}
          </div>
          {{ form.csrf_token }} {% with messages = get_flashed_messages() %} {%
          if messages %}
          <ul
            class="messages"
            style="color: black; font-family: 'Montserrat', sans-serif;text-align:center"
          >
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
          </ul>
          {% endif %} {% endwith %}
          <div
            class="form-group"
            style="font-family: 'Montserrat', sans-serif; font-weight: bolder"
          >
            <input
              class="btn btn-primary"
              id="submit"
              name="submit"
              type="submit"
              value="Register"
            />
          </div>
        </form>
        <a
          href="/login"
          style="
            font-family: 'Montserrat', sans-serif;
            font-weight: bolder;
            color: darkblue;
          "
          >Already have an account? Log In</a
        >
      </div>
    </div>
  </div>
</div>
{% endblock %}